using SA51ADWebApp1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SA51ADWebApp1.Repository
{
    public class Seeder
    {
        public Seeder(Database db)
        {
            Admin admin1 = new Admin();
            admin1.username = "jon";
            admin1.password = "password";
            Admin admin2 = new Admin();
            admin2.username = "zhenli";
            admin2.password = "password";
            Admin admin3 = new Admin();
            admin3.username = "sulp";
            admin3.password = "password";
            Admin admin4 = new Admin();
            admin4.username = "justin";
            admin4.password = "password";
            db.Add(admin1); db.Add(admin2); db.Add(admin3); db.Add(admin4);

            Line yellowLine = new Line();
            yellowLine.lineName = "Circle Line";
            Line redLine = new Line();
            redLine.lineName = "North-South Line";
            Line greenLine = new Line();
            greenLine.lineName = "East-West Line";
            db.Add(yellowLine); db.Add(redLine); db.Add(greenLine);

            Station DhobyGhaut = new Station(); DhobyGhaut.stationName = "Dhoby Ghaut";
            Station BrasBasah = new Station(); BrasBasah.stationName = "Bras Basah";
            Station Esplanade = new Station(); Esplanade.stationName = "Esplanade";
            Station Promenade = new Station(); Promenade.stationName = "Promenade";
            Station NicollHighway = new Station(); NicollHighway.stationName = "Nicoll Highway";
            Station Stadium = new Station(); Stadium.stationName = "Stadium";
            Station Mountbatten = new Station(); Mountbatten.stationName = "Mountbatten";
            Station Dakota = new Station(); Dakota.stationName = "Dakota";
            Station PayaLebar = new Station(); PayaLebar.stationName = "Paya Lebar";
            Station MacPherson = new Station(); MacPherson.stationName = "MacPherson";
            Station TaiSeng = new Station(); TaiSeng.stationName = "Tai Seng";
            Station Bartley = new Station(); Bartley.stationName = "Bartley";
            Station Serangoon = new Station(); Serangoon.stationName = "Serangoon";
            Station LorongChuan = new Station(); LorongChuan.stationName = "Lorong Chuan";
            Station Bishan = new Station(); Bishan.stationName = "Bishan";
            Station Marymount = new Station(); Marymount.stationName = "Marymount";
            Station Caldecott = new Station(); Caldecott.stationName = "Caldecott";
            Station BotanicGardens = new Station(); BotanicGardens.stationName = "Botanic Gardens";
            Station FarrerRoad = new Station(); FarrerRoad.stationName = "Farrer Road";
            Station HollandVillage = new Station(); HollandVillage.stationName = "Holland Village";
            Station BuonaVista = new Station(); BuonaVista.stationName = "Buona Vista";
            Station OneNorth = new Station(); OneNorth.stationName = "one-north";
            Station KentRidge = new Station(); KentRidge.stationName = "Kent Ridge";
            Station HawParVilla = new Station(); HawParVilla.stationName = "Haw Par Villa";
            Station PasirPanjang = new Station(); PasirPanjang.stationName = "Pasir Panjang";
            Station LabradorPark = new Station(); LabradorPark.stationName = "Labrador Park";
            Station TelokBlangah = new Station(); TelokBlangah.stationName = "Telok Blangah";
            Station HarbourFront = new Station(); HarbourFront.stationName = "HarbourFront";
            Station Bayfront = new Station(); Bayfront.stationName = "Bayfront";
            Station MarinaBay = new Station(); MarinaBay.stationName = "Marina Bay";
            db.Add(DhobyGhaut); db.Add(BrasBasah); db.Add(Esplanade); db.Add(Promenade); db.Add(NicollHighway);
            db.Add(Stadium); db.Add(Mountbatten); db.Add(Dakota); db.Add(PayaLebar); db.Add(MacPherson); db.Add(TaiSeng);
            db.Add(Bartley); db.Add(Serangoon); db.Add(LorongChuan); db.Add(Bishan); db.Add(Marymount); db.Add(Caldecott);
            db.Add(BotanicGardens); db.Add(FarrerRoad); db.Add(HollandVillage); db.Add(BuonaVista); db.Add(OneNorth);
            db.Add(KentRidge); db.Add(HawParVilla); db.Add(PasirPanjang); db.Add(LabradorPark); db.Add(TelokBlangah);
            db.Add(HarbourFront); db.Add(Bayfront); db.Add(MarinaBay);

            Station ChangiAirport = new Station(); ChangiAirport.stationName = "Changi Airport";
            Station Expo = new Station(); Expo.stationName = "Expo";
            Station PasirRis = new Station(); PasirRis.stationName = "Pasir Ris";
            Station Tampines = new Station(); Tampines.stationName = "Tampines";
            Station Simei = new Station(); Simei.stationName = "Simei";
            Station TanahMerah = new Station(); TanahMerah.stationName = "Tanah Merah";
            Station Bedok = new Station(); Bedok.stationName = "Bedok";
            Station Kembangan = new Station(); Kembangan.stationName = "Kembangan";
            Station Eunos = new Station(); Eunos.stationName = "Eunos";
            //Station PayaLebar = new Station(); PayaLebar.stationName = "Paya Lebar";
            Station Aljunied = new Station(); Aljunied.stationName = "Aljunied";
            Station Kallang = new Station(); Kallang.stationName = "Kallang";
            Station Lavender = new Station(); Lavender.stationName = "Lavender";
            Station Bugis = new Station(); Bugis.stationName = "Bugis";
            Station CityHall = new Station(); CityHall.stationName = "CityHall";
            Station RafflesPlace = new Station(); RafflesPlace.stationName = "Raffles Place";
            Station TanjongPagar = new Station(); TanjongPagar.stationName = "Tanjong Pagar";
            Station OutramPark = new Station(); OutramPark.stationName = "Outram Park";
            Station TiongBahru = new Station(); TiongBahru.stationName = "Tiong Bahru";
            Station Redhill = new Station(); Redhill.stationName = "Redhill";
            Station Queenstown = new Station(); Queenstown.stationName = "Queenstown";
            Station Commonwealth = new Station(); Commonwealth.stationName = "Commonwealth";
            //Station BuonaVista = new Station(); BuonaVista.stationName = "Buona Vista";
            Station Dover = new Station(); Dover.stationName = "Dover";
            Station Clementi = new Station(); Clementi.stationName = "Clementi";
            Station JurongEast = new Station(); JurongEast.stationName = "Jurong East";
            Station ChineseGarden = new Station(); ChineseGarden.stationName = "Chinese Garden";
            Station Lakeside = new Station(); Lakeside.stationName = "Lakeside";
            Station BoonLay = new Station(); BoonLay.stationName = "Boon Lay";
            Station Pioneer = new Station(); Pioneer.stationName = "Pioneer";
            Station JooKoon = new Station(); JooKoon.stationName = "Joo Koon";
            Station GulCircle = new Station(); GulCircle.stationName = "Gul Circle";
            Station TuasCrescent = new Station(); TuasCrescent.stationName = "Tuas Crescent";
            Station TuasWestRoad = new Station(); TuasWestRoad.stationName = "Tuas West Road";
            Station TuasLink = new Station(); TuasLink.stationName = "Tuas Link";
            db.Add(ChangiAirport); db.Add(Expo); db.Add(PasirRis); db.Add(Tampines); db.Add(Simei); db.Add(TanahMerah);
            db.Add(Bedok); db.Add(Kembangan); db.Add(Eunos); db.Add(Aljunied); db.Add(Kallang); db.Add(Lavender); db.Add(Bugis);
            db.Add(CityHall); db.Add(RafflesPlace); db.Add(TanjongPagar); db.Add(OutramPark); db.Add(TiongBahru); db.Add(Redhill);
            db.Add(Queenstown); db.Add(Commonwealth); db.Add(Dover); db.Add(Clementi); db.Add(JurongEast); db.Add(ChineseGarden);
            db.Add(Lakeside); db.Add(BoonLay); db.Add(Pioneer); db.Add(JooKoon); db.Add(GulCircle); db.Add(TuasCrescent);
            db.Add(TuasWestRoad); db.Add(TuasLink);

            //Station JurongEast = new Station(); JurongEast.stationName = "Jurong East";
            Station BukitBatok = new Station(); BukitBatok.stationName = "Bukit Batok";
            Station BukitGombak = new Station(); BukitGombak.stationName = "Bukit Gombak";
            Station ChoaChuKang = new Station(); ChoaChuKang.stationName = "Choa Chu Kang";
            Station YewTee = new Station(); YewTee.stationName = "Yew Tee ";
            Station Kranji = new Station(); Kranji.stationName = "Kranji";
            Station Marsiling = new Station(); Marsiling.stationName = "Marsiling";
            Station Woodlands = new Station(); Woodlands.stationName = "Woodlands";
            Station Admiralty = new Station(); Admiralty.stationName = "Admiralty";
            Station Sembawang = new Station(); Sembawang.stationName = "Sembawang";
            Station Canberra = new Station(); Canberra.stationName = "Canberra";
            Station Yishun = new Station(); Yishun.stationName = "Yishun";
            Station Khatib = new Station(); Khatib.stationName = "Khatib";
            Station YioChuKang = new Station(); YioChuKang.stationName = "Yio Chu Kang";
            Station AngMoKio = new Station(); AngMoKio.stationName = "Ang Mo Kio";
            //Station Bishan = new Station(); Bishan.stationName = "Bishan";
            Station Braddell = new Station(); Braddell.stationName = "Braddell";
            Station ToaPayoh = new Station(); ToaPayoh.stationName = "Toa Payoh";
            Station Novena = new Station(); Novena.stationName = "Novena";
            Station Newton = new Station(); Newton.stationName = "Newton";
            Station Orchard = new Station(); Orchard.stationName = "Orchard";
            Station Somerset = new Station(); Somerset.stationName = "Somerset";
            //Station DhobyGhaut = new Station(); DhobyGhaut.stationName = "Dhoby Ghaut";
            //Station CityHall = new Station(); CityHall.stationName = "City Hall";
            //Station RafflesPlace = new Station(); RafflesPlace.stationName = "Raffles Place";
            //Station MarinaBay = new Station(); MarinaBay.stationName = "Marina Bay";
            Station MarinaSouthPier = new Station(); MarinaSouthPier.stationName = "Marina South Pier";
            db.Add(BukitBatok); db.Add(BukitGombak); db.Add(ChoaChuKang); db.Add(YewTee); db.Add(Kranji); db.Add(Marsiling);
            db.Add(Woodlands); db.Add(Admiralty); db.Add(Sembawang); db.Add(Canberra); db.Add(Yishun); db.Add(Khatib);
            db.Add(YioChuKang); db.Add(AngMoKio); db.Add(Braddell); db.Add(ToaPayoh); db.Add(Novena); db.Add(Newton);
            db.Add(Orchard); db.Add(Somerset); db.Add(MarinaSouthPier);

            db.SaveChanges();

            //Uncomment the btm three lines to test
            StationOnLine NS1 = new StationOnLine(); NS1.LineId = redLine.Id; NS1.StationId = JurongEast.Id; NS1.stationCode = "NS1"; 
            NS1.status = "Operational"; NS1.timeToNextStation = 0; NS1.timeToNextStationOpp = 3;
            db.Add(NS1);
            StationOnLine NS2 = new StationOnLine(); NS2.LineId = redLine.Id; NS2.StationId = BukitBatok.Id; NS2.stationCode = "NS2";
            NS2.status = "Operational"; NS2.timeToNextStation = 3; NS2.timeToNextStationOpp = 2;
            db.Add(NS2);
            StationOnLine NS3 = new StationOnLine(); NS3.LineId = redLine.Id; NS3.StationId = BukitGombak.Id; NS3.stationCode = "NS3";
            NS3.status = "Operational"; NS3.timeToNextStation = 2; NS3.timeToNextStationOpp = 4;
            db.Add(NS3);
            StationOnLine NS4 = new StationOnLine(); NS4.LineId = redLine.Id; NS4.StationId = ChoaChuKang.Id; NS4.stationCode = "NS4";
            NS4.status = "Operational"; NS4.timeToNextStation = 4; NS4.timeToNextStationOpp = 3;
            db.Add(NS4);
            StationOnLine NS5 = new StationOnLine(); NS5.LineId = redLine.Id; NS5.StationId = YewTee.Id; NS5.stationCode = "NS5";
            NS5.status = "Operational"; NS5.timeToNextStation = 3; NS5.timeToNextStationOpp = 5;
            db.Add(NS5);
            StationOnLine NS7 = new StationOnLine(); NS7.LineId = redLine.Id; NS7.StationId = Kranji.Id; NS7.stationCode = "NS7";
            NS7.status = "Operational"; NS7.timeToNextStation = 5; NS7.timeToNextStationOpp = 3;
            db.Add(NS7);
            StationOnLine NS8 = new StationOnLine(); NS8.LineId = redLine.Id; NS8.StationId = Marsiling.Id; NS8.stationCode = "NS8";
            NS8.status = "Operational"; NS8.timeToNextStation = 3; NS8.timeToNextStationOpp = 2;
            db.Add(NS8);
            StationOnLine NS9 = new StationOnLine(); NS9.LineId = redLine.Id; NS9.StationId = Woodlands.Id; NS9.stationCode = "NS9";
            NS9.status = "Operational"; NS9.timeToNextStation = 2; NS9.timeToNextStationOpp = 3;
            db.Add(NS9);
            StationOnLine NS10 = new StationOnLine(); NS10.LineId = redLine.Id; NS10.StationId = Admiralty.Id; NS10.stationCode = "NS10";
            NS10.status = "Operational"; NS10.timeToNextStation = 3; NS10.timeToNextStationOpp = 3;
            db.Add(NS10);
            StationOnLine NS11 = new StationOnLine(); NS11.LineId = redLine.Id; NS11.StationId = Sembawang.Id; NS11.stationCode = "NS11";
            NS11.status = "Operational"; NS11.timeToNextStation = 3; NS11.timeToNextStationOpp = 3;
            db.Add(NS11);
            StationOnLine NS12 = new StationOnLine(); NS12.LineId = redLine.Id; NS12.StationId = Canberra.Id; NS12.stationCode = "NS12";
            NS12.status = "Operational"; NS12.timeToNextStation = 3; NS12.timeToNextStationOpp = 3;
            db.Add(NS12);
            StationOnLine NS13 = new StationOnLine(); NS13.LineId = redLine.Id; NS13.StationId = Yishun.Id; NS13.stationCode = "NS13";
            NS13.status = "Operational"; NS13.timeToNextStation = 3; NS13.timeToNextStationOpp = 2;
            db.Add(NS13);
            StationOnLine NS14 = new StationOnLine(); NS14.LineId = redLine.Id; NS14.StationId = Khatib.Id; NS14.stationCode = "NS14";
            NS14.status = "Operational"; NS14.timeToNextStation = 2; NS14.timeToNextStationOpp = 6;
            db.Add(NS14);
            StationOnLine NS15 = new StationOnLine(); NS15.LineId = redLine.Id; NS15.StationId = YioChuKang.Id; NS15.stationCode = "NS15";
            NS15.status = "Operational"; NS15.timeToNextStation = 6; NS15.timeToNextStationOpp = 2;
            db.Add(NS15);
            StationOnLine NS16 = new StationOnLine(); NS16.LineId = redLine.Id; NS16.StationId = AngMoKio.Id; NS16.stationCode = "NS16";
            NS16.status = "Operational"; NS16.timeToNextStation = 2; NS16.timeToNextStationOpp = 4;
            db.Add(NS16);
            StationOnLine NS17 = new StationOnLine(); NS17.LineId = redLine.Id; NS17.StationId = Bishan.Id; NS17.stationCode = "NS17";
            NS17.status = "Operational"; NS17.timeToNextStation = 4; NS17.timeToNextStationOpp = 2;
            db.Add(NS17);
            StationOnLine NS18 = new StationOnLine(); NS18.LineId = redLine.Id; NS18.StationId = Braddell.Id; NS18.stationCode = "NS18";
            NS18.status = "Operational"; NS18.timeToNextStation = 2; NS18.timeToNextStationOpp = 2;
            db.Add(NS18);
            StationOnLine NS19 = new StationOnLine(); NS19.LineId = redLine.Id; NS19.StationId = ToaPayoh.Id; NS19.stationCode = "NS19";
            NS19.status = "Operational"; NS19.timeToNextStation = 2; NS19.timeToNextStationOpp = 3;
            db.Add(NS19);
            StationOnLine NS20 = new StationOnLine(); NS20.LineId = redLine.Id; NS20.StationId = Novena.Id; NS20.stationCode = "NS20";
            NS20.status = "Operational"; NS20.timeToNextStation = 3; NS20.timeToNextStationOpp = 2;
            db.Add(NS20);
            StationOnLine NS21 = new StationOnLine(); NS21.LineId = redLine.Id; NS21.StationId = Newton.Id; NS21.stationCode = "NS21";
            NS21.status = "Operational"; NS21.timeToNextStation = 2; NS21.timeToNextStationOpp = 3;
            db.Add(NS21);
            StationOnLine NS22 = new StationOnLine(); NS22.LineId = redLine.Id; NS22.StationId = Orchard.Id; NS22.stationCode = "NS22";
            NS22.status = "Operational"; NS22.timeToNextStation = 3; NS22.timeToNextStationOpp = 2;
            db.Add(NS22);
            StationOnLine NS23 = new StationOnLine(); NS23.LineId = redLine.Id; NS23.StationId = Somerset.Id; NS23.stationCode = "NS23";
            NS23.status = "Operational"; NS23.timeToNextStation = 2; NS23.timeToNextStationOpp = 2;
            db.Add(NS23);
            StationOnLine NS24 = new StationOnLine(); NS24.LineId = redLine.Id; NS24.StationId = DhobyGhaut.Id; NS24.stationCode = "NS24";
            NS24.status = "Operational"; NS24.timeToNextStation = 2; NS24.timeToNextStationOpp = 3;
            db.Add(NS24);
            StationOnLine NS25 = new StationOnLine(); NS25.LineId = redLine.Id; NS25.StationId = CityHall.Id; NS25.stationCode = "NS25";
            NS25.status = "Operational"; NS25.timeToNextStation = 3; NS25.timeToNextStationOpp = 2;
            db.Add(NS25);
            StationOnLine NS26 = new StationOnLine(); NS26.LineId = redLine.Id; NS26.StationId = RafflesPlace.Id; NS26.stationCode = "NS26";
            NS26.status = "Operational"; NS26.timeToNextStation = 2; NS26.timeToNextStationOpp = 2;
            db.Add(NS26);
            StationOnLine NS27 = new StationOnLine(); NS27.LineId = redLine.Id; NS27.StationId = MarinaBay.Id; NS27.stationCode = "NS27";
            NS27.status = "Operational"; NS27.timeToNextStation = 2; NS27.timeToNextStationOpp = 3;
            db.Add(NS27);
            StationOnLine NS28 = new StationOnLine(); NS28.LineId = redLine.Id; NS28.StationId = MarinaSouthPier.Id; NS28.stationCode = "NS28";
            NS28.status = "Operational"; NS28.timeToNextStation = 3; NS28.timeToNextStationOpp = 0;
            db.Add(NS28);

            db.SaveChanges();
        }
    }
}
